baseurl = "https://wiki.openmindsclub.net"
metaDataFormat = "yaml"
title = "OpenWiki"
theme = "blist"

DefaultContentLanguage = "fr"
DefaultContentLanguageInSubdir = false
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Welcome to the Free Open Source Wiki !"
      introSubtitle = "OpenMindsClub is an Algerian Student Club passionate about Free Open Source. We post tutorials, dissertations, reviews and articles. Stick around for long enough and you might find something you would enjoy reading !"
      introPhoto = "/bg.jpg"
      logo = "/logo-light.png"
      logoDark = "/logo-dark.png"
    [[languages.en.menu.main]]
        name = "Posts"
        url = "posts"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Contribute"
        url = "posts/contribute-to-openwiki/"
        weight = 4

    [[languages.en.menu.main]]
        name = "Contributors"
        url = "page/contributors/"
        weight = 5


  [languages.fr]
    contentDir = "content/fr" #French
    weight = 1
    languageName = "Français"
    [languages.fr.params]
       introTitle = "Bienvenu à la Wiki du Libre Open Source !"
      introSubtitle = "OpenMindsClub est un club estudiantin algérien passionné par le Libre Open Source. Nous publions des tutoriels, des dissertations, des critiques et des articles. N'hésitez pas à jeter un coup d'œil sur nos postes... vous pourriez trouver quelque chose qui vous conviendra !"
      introPhoto = "/bg.jpg"
      logo = "/logo-light.png"
      logoDark = "/logo-dark.png"
    [[languages.fr.menu.main]]
        name = "Postes"
        url = "posts"
        weight = 1

    [[languages.fr.menu.main]]
        name = "À propos"
        url = "page/about/"
        weight = 2

    [[languages.fr.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.fr.menu.main]]
        name = "Contribuer"
        url = "fr/posts/contribute-to-openwiki/"
        weight = 4

    [[languages.fr.menu.main]]
        name = "Contributeurs"
        url = "page/contributors/"
        weight = 5

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Attribution-ShareAlike 3.0 Unported · 2022 · Humans of OpenMindsClub"
  favicon = "/favicon.png"

  # Color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-gray-900"

  # The page bundle that is shown on the front page
  frontBundle = "posts"

[params.homepage.social]
  # Global params xommon for both languages
  title = "Follow us"
  description = "We do everything from projects, lectures, courses, workshops and events. Follow us closely to know more !"
  twitter = "https://twitter.com/clubopenminds"
  linkedin = "https://linkedin.com/company/open-minds-club"
  github = "https://github.com/openmindsclub"
  youtube = "https://www.youtube.com/c/OpenMindsClubOMC"
  facebook = "https://facebook.com/openmindsclub"
  instagram = "https://instagram.com/openmindsclub"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
